version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - ./symfony-project:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony-network

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony-project:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony-network

  postgres:
    image: postgres:latest
    container_name: database_postgres
    environment:
      POSTGRES_DB: exams
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
